site_name: From PPO to GRPO — Beginner Guide
theme:
  name: material
  language: en
nav:
  - Home: index.md
  - 1. RL Basics: 01_RLBasics.md
  - 2. PPO Theory: 02_PPOTheory.md
  - 3. GRPO Theory: 03_GRPOTheory.md
  - 4. Code Analysis: 04_CodeAnalysis.md
  - 5. Other RL Methods: 05_OtherRLMethods.md
